const std = @import("std");
const Io = std.Io;

const hip = @import("hip");

const HipError = error{
    InvalidValue,
    OutOfMemory,
    NotInitialized,
    Deinitialized,
    ProfilerDisabled,
    ProfilerNotInitialized,
    ProfilerAlreadyStarted,
    ProfilerAlreadyStopped,
    InvalidConfiguration,
    InvalidPitchValue,
    InvalidSymbol,
    InvalidDevicePointer,
    InvalidMemcpyDirection,
    InsufficientDriver,
    MissingConfiguration,
    PriorLaunchFailure,
    InvalidDeviceFunction,
    NoDevice,
    InvalidDevice,
    InvalidImage,
    InvalidContext,
    ContextAlreadyCurrent,
    MapFailed,
    UnmapFailed,
    ArrayIsMapped,
    AlreadyMapped,
    NoBinaryForGpu,
    AlreadyAcquired,
    NotMapped,
    NotMappedAsArray,
    NotMappedAsPointer,
    ECCNotCorrectable,
    UnsupportedLimit,
    ContextAlreadyInUse,
    PeerAccessUnsupported,
    InvalidKernelFile,
    InvalidGraphicsContext,
    InvalidSource,
    FileNotFound,
    SharedObjectSymbolNotFound,
    SharedObjectInitFailed,
    OperatingSystem,
    InvalidHandle,
    IllegalState,
    NotFound,
    NotReady,
    IllegalAddress,
    LaunchOutOfResources,
    LaunchTimeOut,
    PeerAccessAlreadyEnabled,
    PeerAccessNotEnabled,
    SetOnActiveProcess,
    ContextIsDestroyed,
    Assert,
    HostMemoryAlreadyRegistered,
    HostMemoryNotRegistered,
    LaunchFailure,
    CooperativeLaunchTooLarge,
    NotSupported,
    StreamCaptureUnsupported,
    StreamCaptureInvalidated,
    StreamCaptureMerge,
    StreamCaptureUnmatched,
    StreamCaptureUnjoined,
    StreamCaptureIsolation,
    StreamCaptureImplicit,
    CapturedEvent,
    StreamCaptureWrongThread,
    GraphExecUpdateFailure,
    InvalidChannelDescriptor,
    InvalidTexture,
    Unknown,
    RuntimeMemory,
    RuntimeOther,
    ToBeDetermined,
};

pub fn bubbleWrap(value: hip.HipError) HipError!void {
    return switch (value) {
        hip.hip_success => {},
        hip.hip_error_invalid_value => HipError.InvalidValue,
        hip.hip_error_out_of_memory => HipError.OutOfMemory,
        hip.hip_error_not_initialized => HipError.NotInitialized,
        hip.hip_error_deinitialized => HipError.Deinitialized,
        hip.hip_error_profiler_disabled => HipError.ProfilerDisabled,
        hip.hip_error_profiler_not_initialized => HipError.ProfilerNotInitialized,
        hip.hip_error_profiler_already_started => HipError.ProfilerAlreadyStarted,
        hip.hip_error_profiler_already_stopped => HipError.ProfilerAlreadyStopped,
        hip.hip_error_invalid_configuration => HipError.InvalidConfiguration,
        hip.hip_error_invalid_pitch_value => HipError.InvalidPitchValue,
        hip.hip_error_invalid_symbol => HipError.InvalidSymbol,
        hip.hip_error_invalid_device_pointer => HipError.InvalidDevicePointer,
        hip.hip_error_invalid_memcpy_direction => HipError.InvalidMemcpyDirection,
        hip.hip_error_insufficient_driver => HipError.InsufficientDriver,
        hip.hip_error_missing_configuration => HipError.MissingConfiguration,
        hip.hip_error_prior_launch_failure => HipError.PriorLaunchFailure,
        hip.hip_error_invalid_device_function => HipError.InvalidDeviceFunction,
        hip.hip_error_no_device => HipError.NoDevice,
        hip.hip_error_invalid_device => HipError.InvalidDevice,
        hip.hip_error_invalid_image => HipError.InvalidImage,
        hip.hip_error_invalid_context => HipError.InvalidContext,
        hip.hip_error_context_already_current => HipError.ContextAlreadyCurrent,
        hip.hip_error_map_failed => HipError.MapFailed,
        hip.hip_error_unmap_failed => HipError.UnmapFailed,
        hip.hip_error_array_is_mapped => HipError.ArrayIsMapped,
        hip.hip_error_already_mapped => HipError.AlreadyMapped,
        hip.hip_error_no_binary_for_gpu => HipError.NoBinaryForGpu,
        hip.hip_error_already_acquired => HipError.AlreadyAcquired,
        hip.hip_error_not_mapped => HipError.NotMapped,
        hip.hip_error_not_mapped_as_array => HipError.NotMappedAsArray,
        hip.hip_error_not_mapped_as_pointer => HipError.NotMappedAsPointer,
        hip.hip_error_e_c_c_not_correctable => HipError.ECCNotCorrectable,
        hip.hip_error_unsupported_limit => HipError.UnsupportedLimit,
        hip.hip_error_context_already_in_use => HipError.ContextAlreadyInUse,
        hip.hip_error_peer_access_unsupported => HipError.PeerAccessUnsupported,
        hip.hip_error_invalid_kernel_file => HipError.InvalidKernelFile,
        hip.hip_error_invalid_graphics_context => HipError.InvalidGraphicsContext,
        hip.hip_error_invalid_source => HipError.InvalidSource,
        hip.hip_error_file_not_found => HipError.FileNotFound,
        hip.hip_error_shared_object_symbol_not_found => HipError.SharedObjectSymbolNotFound,
        hip.hip_error_shared_object_init_failed => HipError.SharedObjectInitFailed,
        hip.hip_error_operating_system => HipError.OperatingSystem,
        hip.hip_error_invalid_handle => HipError.InvalidHandle,
        hip.hip_error_illegal_state => HipError.IllegalState,
        hip.hip_error_not_found => HipError.NotFound,
        hip.hip_error_not_ready => HipError.NotReady,
        hip.hip_error_illegal_address => HipError.IllegalAddress,
        hip.hip_error_launch_out_of_resources => HipError.LaunchOutOfResources,
        hip.hip_error_launch_time_out => HipError.LaunchTimeOut,
        hip.hip_error_peer_access_already_enabled => HipError.PeerAccessAlreadyEnabled,
        hip.hip_error_peer_access_not_enabled => HipError.PeerAccessNotEnabled,
        hip.hip_error_set_on_active_process => HipError.SetOnActiveProcess,
        hip.hip_error_context_is_destroyed => HipError.ContextIsDestroyed,
        hip.hip_error_assert => HipError.Assert,
        hip.hip_error_host_memory_already_registered => HipError.HostMemoryAlreadyRegistered,
        hip.hip_error_host_memory_not_registered => HipError.HostMemoryNotRegistered,
        hip.hip_error_launch_failure => HipError.LaunchFailure,
        hip.hip_error_cooperative_launch_too_large => HipError.CooperativeLaunchTooLarge,
        hip.hip_error_not_supported => HipError.NotSupported,
        hip.hip_error_stream_capture_unsupported => HipError.StreamCaptureUnsupported,
        hip.hip_error_stream_capture_invalidated => HipError.StreamCaptureInvalidated,
        hip.hip_error_stream_capture_merge => HipError.StreamCaptureMerge,
        hip.hip_error_stream_capture_unmatched => HipError.StreamCaptureUnmatched,
        hip.hip_error_stream_capture_unjoined => HipError.StreamCaptureUnjoined,
        hip.hip_error_stream_capture_isolation => HipError.StreamCaptureIsolation,
        hip.hip_error_stream_capture_implicit => HipError.StreamCaptureImplicit,
        hip.hip_error_captured_event => HipError.CapturedEvent,
        hip.hip_error_stream_capture_wrong_thread => HipError.StreamCaptureWrongThread,
        hip.hip_error_graph_exec_update_failure => HipError.GraphExecUpdateFailure,
        hip.hip_error_invalid_channel_descriptor => HipError.InvalidChannelDescriptor,
        hip.hip_error_invalid_texture => HipError.InvalidTexture,
        hip.hip_error_unknown => HipError.Unknown,
        hip.hip_error_runtime_memory => HipError.RuntimeMemory,
        hip.hip_error_runtime_other => HipError.RuntimeOther,
        else => HipError.ToBeDetermined,
    };
}

pub fn main(_: std.process.Init) !void {
    std.debug.print("Cpp returned: {any}.\n", .{hip.add(4, 6)});

    var hipStream: hip.HipStream = undefined;
    try bubbleWrap(hip.createHipStream(&hipStream));
    defer hip.destroyHipStream(hipStream);
}
